default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: devbootcamp_challenge_development

test:
  <<: *default
  database: devbootcamp_challenge_test

production:
  <<: *default
  database: devbootcamp_challenge_production
  username: devbootcamp_challenge
  password: <%= ENV['DEVBOOTCAMP_CHALLENGE_DATABASE_PASSWORD'] %>
